### ISSUE TITLE
关于使用makefile/cmakelists组织构建

### ISSUE THREAD

**Issue by babywade** [changgang/steps#1]
当前构建依赖于cbp2make工具，建议直接使用cmakelists组织构建；
代码开发环境可使用vscode；

**Comment by changgang** [comment]
这是非常好的主意。
目前主要是在Code::Blocks环境下开发STEPS，make工具只是在有些应用环境不提供图形界面时才会用到，所以用cbp2make将Code::Blocks工程转为make下的代码组织。
后面我会考虑直接采用makelist进行代码组织。
