### ISSUE TITLE
While Creating libSTEPS.dll getting error |16|error: 'mutex' in namespace 'std' does not name a type|

### ISSUE THREAD

**Issue by Adarsh-365** [changgang/steps#2]
I have successfully created libCpptest.a libCSparse.a libCXSparse.a but for creating  libSTEPS.dll I am facing the following errors

![Screenshot (172)](https://github.com/changgang/steps/assets/102159256/5370df12-dacb-40c1-a7c2-9d3aca56de0e)

**Comment by changgang** [comment]
I think this is a compiler problem. You need to choose proper compiler.
See the following link when you use Windows. It works if I use the latest [MinGW-64](http://mingw-w64.org/) compiler.
https://github.com/changgang/steps/wiki/How-to-build-STEPS-kernel#windows-system

**Comment by fight-ning** [comment]
Dear author, I have two questions that I hope you can answer when convenient. 1. After loading a PSSE file, how can I extract the internal base parameters? 2. What are the optional parameter names for certain commands, such as in the command "simulator.get_transformer_data("d", "transformer", par_name)," what are the possible values for "par_name"?
